//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ideal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Employee
    {
        public string EMP_ID { get; set; }
        public string NAME { get; set; }
        public string WORKGROUP { get; set; }
        public Nullable<System.DateTime> ENTER_DATE { get; set; }
    }
}
